<Project Sdk="Godot.NET.Sdk/4.4.0-dev.7">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>
  <ItemGroup>
    <!-- Other NuGet package references -->
    <PackageReference Include="Thirdweb" Version="2.12.1" />
    <!-- Update with the latest version when necessary -->
  </ItemGroup>
</Project>